export const SHORT_CODE_LENGTH = Number(process.env.SHORT_CODE_LENGTH ?? 6);
export const BASE_URL =
  process.env.NEXT_PUBLIC_SHORT_URL_BASE ?? "http://localhost:3000";

export const VALID_SOURCES = [
  "direct",
  "referral",
  "social",
  "search",
  "email",
  "other",
  "unknown"
] as const;
export const VALID_DEVICES = [
  "mobile",
  "desktop",
  "tablet",
  "unknown"
] as const;

/**
 * Environment validation constants
 * Configuration for production deployment requirements
 */

export const REQUIRED_ENV_VARIABLES = [
  "DATABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY"
] as const;

export const ENVIRONMENT_PRODUCTION = "production";
export const ENVIRONMENT_PREVIEW = "preview";
export const ENVIRONMENT_LOCAL = "local";

/**
 * Error code constants for environment validation
 */
export const ERROR_CODES = {
  MISSING_DATABASE_URL: "MISSING_DATABASE_URL",
  INVALID_DATABASE_URL_FORMAT: "INVALID_DATABASE_URL_FORMAT",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  MISSING_SUPABASE_ANON_KEY: "MISSING_SUPABASE_ANON_KEY",
  INVALID_SUPABASE_ANON_KEY_FORMAT: "INVALID_SUPABASE_ANON_KEY_FORMAT",
  MISSING_SUPABASE_SERVICE_ROLE_KEY: "MISSING_SUPABASE_SERVICE_ROLE_KEY",
  INVALID_SUPABASE_SERVICE_ROLE_KEY_FORMAT: "INVALID_SUPABASE_SERVICE_ROLE_KEY_FORMAT",
  ENVIRONMENT_VALIDATION_FAILED: "ENVIRONMENT_VALIDATION_FAILED",
  DEPLOYMENT_UNHEALTHY: "DEPLOYMENT_UNHEALTHY",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  ENV_VALIDATION_FAILED: "ENV_VALIDATION_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS"
} as const;
